controllers:
    resource: ../src/Controller/
    type: attribute

inici:
    resource: ../src/Controller/IniciController.php
    type: annotation

equips:
    resource: ../src/Controller/EquipsController.php
    type: annotation

